<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nikita Muddapati">

<title>Home Credit Default Risk: Modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="modelling_nikita_pdf_files/libs/clipboard/clipboard.min.js"></script>
<script src="modelling_nikita_pdf_files/libs/quarto-html/quarto.js"></script>
<script src="modelling_nikita_pdf_files/libs/quarto-html/popper.min.js"></script>
<script src="modelling_nikita_pdf_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="modelling_nikita_pdf_files/libs/quarto-html/anchor.min.js"></script>
<link href="modelling_nikita_pdf_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="modelling_nikita_pdf_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="modelling_nikita_pdf_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="modelling_nikita_pdf_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="modelling_nikita_pdf_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#data-setup" id="toc-data-setup" class="nav-link active" data-scroll-target="#data-setup">Data Setup</a>
  <ul class="collapse">
  <li><a href="#clean-train-data" id="toc-clean-train-data" class="nav-link" data-scroll-target="#clean-train-data">Clean Train Data</a></li>
  <li><a href="#clean-test-data" id="toc-clean-test-data" class="nav-link" data-scroll-target="#clean-test-data">Clean Test Data</a></li>
  </ul></li>
  <li><a href="#class-imbalance" id="toc-class-imbalance" class="nav-link" data-scroll-target="#class-imbalance">Class Imbalance</a></li>
  <li><a href="#non-linear-separability-check" id="toc-non-linear-separability-check" class="nav-link" data-scroll-target="#non-linear-separability-check">Non-Linear Separability Check</a></li>
  <li><a href="#data-split" id="toc-data-split" class="nav-link" data-scroll-target="#data-split">Data Split</a></li>
  <li><a href="#logistic-regression-performance" id="toc-logistic-regression-performance" class="nav-link" data-scroll-target="#logistic-regression-performance">Logistic Regression Performance</a></li>
  <li><a href="#xgboost" id="toc-xgboost" class="nav-link" data-scroll-target="#xgboost">XGBoost</a>
  <ul class="collapse">
  <li><a href="#define-model" id="toc-define-model" class="nav-link" data-scroll-target="#define-model">Define Model</a>
  <ul class="collapse">
  <li><a href="#define-recipe" id="toc-define-recipe" class="nav-link" data-scroll-target="#define-recipe">Define Recipe</a></li>
  <li><a href="#define-grid-search-parameter-tuning-and-cv-function" id="toc-define-grid-search-parameter-tuning-and-cv-function" class="nav-link" data-scroll-target="#define-grid-search-parameter-tuning-and-cv-function">Define Grid search parameter tuning and CV function</a></li>
  </ul></li>
  <li><a href="#train-the-model" id="toc-train-the-model" class="nav-link" data-scroll-target="#train-the-model">Train the Model</a></li>
  <li><a href="#evaluate-model" id="toc-evaluate-model" class="nav-link" data-scroll-target="#evaluate-model">Evaluate Model</a>
  <ul class="collapse">
  <li><a href="#identify-best-hyperparameters-and-finalize-workflow" id="toc-identify-best-hyperparameters-and-finalize-workflow" class="nav-link" data-scroll-target="#identify-best-hyperparameters-and-finalize-workflow">Identify best hyperparameters and finalize Workflow</a></li>
  <li><a href="#evaluate-on-train-data" id="toc-evaluate-on-train-data" class="nav-link" data-scroll-target="#evaluate-on-train-data">Evaluate on Train Data</a></li>
  <li><a href="#evaluate-on-test-data" id="toc-evaluate-on-test-data" class="nav-link" data-scroll-target="#evaluate-on-test-data">Evaluate on Test Data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#feature-importance" id="toc-feature-importance" class="nav-link" data-scroll-target="#feature-importance">Feature Importance</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#make-predictions-with-the-test-application-data" id="toc-make-predictions-with-the-test-application-data" class="nav-link" data-scroll-target="#make-predictions-with-the-test-application-data">Make Predictions with the Test Application Data</a></li>
  </ul></li>
  <li><a href="#format-the-predictions-into-an-acceptable-format-for-kaggle" id="toc-format-the-predictions-into-an-acceptable-format-for-kaggle" class="nav-link" data-scroll-target="#format-the-predictions-into-an-acceptable-format-for-kaggle">Format the predictions into an acceptable format for Kaggle</a>
  <ul class="collapse">
  <li><a href="#final-interpretations-and-conclusion" id="toc-final-interpretations-and-conclusion" class="nav-link" data-scroll-target="#final-interpretations-and-conclusion">Final Interpretations and Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Home Credit Default Risk: Modelling</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nikita Muddapati </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="data-setup" class="level1">
<h1>Data Setup</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,skimr,janitor,knitr,caret,rminer,mice,dbscan,tictoc,dplyr,ranger,psych, tidymodels, ggplot2, scales, fastDummies,caret)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Matrix)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)   <span class="co"># to plot ROC-AUC</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)  <span class="co"># for svm</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally) <span class="co"># to plot with ggpairs()</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doParallel)  <span class="co"># for training xgboost using parallel processing</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MLmetrics)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(themis)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rmarkdown)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load cleaned application_train and application_test data from EDA HW (with removed columns, NA's, outliers)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>train_clean <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project/train_clean.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>test_clean <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project/test_clean.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_clean)  <span class="co">#first 6 rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 64
  SK_ID_CURR TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY
       &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;          
1     100002      1 Cash loans         M           N            Y              
2     100003      0 Cash loans         F           N            N              
3     100006      0 Cash loans         F           N            Y              
4     100007      0 Cash loans         M           N            Y              
5     100008      0 Cash loans         M           N            Y              
6     100011      0 Cash loans         F           N            Y              
# ℹ 58 more variables: CNT_CHILDREN &lt;dbl&gt;, AMT_INCOME_TOTAL &lt;dbl&gt;,
#   AMT_CREDIT &lt;dbl&gt;, AMT_ANNUITY &lt;dbl&gt;, AMT_GOODS_PRICE &lt;dbl&gt;,
#   NAME_TYPE_SUITE &lt;chr&gt;, NAME_INCOME_TYPE &lt;chr&gt;, NAME_EDUCATION_TYPE &lt;chr&gt;,
#   NAME_FAMILY_STATUS &lt;chr&gt;, NAME_HOUSING_TYPE &lt;chr&gt;,
#   REGION_POPULATION_RELATIVE &lt;dbl&gt;, DAYS_BIRTH &lt;dbl&gt;,
#   DAYS_REGISTRATION &lt;dbl&gt;, DAYS_ID_PUBLISH &lt;dbl&gt;, OWN_CAR_AGE &lt;dbl&gt;,
#   FLAG_EMP_PHONE &lt;dbl&gt;, FLAG_WORK_PHONE &lt;dbl&gt;, FLAG_PHONE &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train_clean)  <span class="co">#shape of data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 237776     64</code></pre>
</div>
</div>
<section id="clean-train-data" class="level2">
<h2 class="anchored" data-anchor-id="clean-train-data">Clean Train Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove identifier</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>train_clean <span class="ot">&lt;-</span> train_clean <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>SK_ID_CURR) </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># factor target  </span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#train_clean$TARGET &lt;- factor(train_clean$TARGET, levels = c(0, 1))</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Modify all character variables into factors</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>tr_clean <span class="ot">&lt;-</span> train_clean <span class="sc">%&gt;%</span> </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate_if</span>(is.character, as.factor)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Store all numeric variables which should be factors in a vector</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>num_cat_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"TARGET"</span>,<span class="st">"FLAG_EMP_PHONE"</span>,<span class="st">"FLAG_WORK_PHONE"</span>,<span class="st">"FLAG_EMAIL"</span>,<span class="st">"FLAG_PHONE"</span>,<span class="st">'REG_REGION_NOT_WORK_REGION'</span>,<span class="st">'LIVE_CITY_NOT_WORK_CITY'</span>,<span class="st">"REG_CITY_NOT_LIVE_CITY"</span>,<span class="st">"REG_CITY_NOT_WORK_CITY"</span>,<span class="st">"REGION_RATING_CLIENT_W_CITY"</span>,<span class="st">"FLAG_DOCUMENT_3"</span>,<span class="st">"FLAG_DOCUMENT_6"</span>,<span class="st">"FLAG_DOCUMENT_8"</span>,<span class="st">"REGION_RATING_CLIENT"</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># transform the vector of num. columns to factors</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>tr_clean <span class="ot">&lt;-</span> train_clean <span class="sc">%&gt;%</span> </span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(num_cat_values), as.factor))</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="co"># structure of target</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tr_clean<span class="sc">$</span>TARGET) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 2 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of cleaned dataset</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tr_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> TARGET     NAME_CONTRACT_TYPE CODE_GENDER        FLAG_OWN_CAR      
 0:218531   Length:237776      Length:237776      Length:237776     
 1: 19245   Class :character   Class :character   Class :character  
            Mode  :character   Mode  :character   Mode  :character  
                                                                    
                                                                    
                                                                    
 FLAG_OWN_REALTY     CNT_CHILDREN    AMT_INCOME_TOTAL   AMT_CREDIT     
 Length:237776      Min.   :0.0000   Min.   : 25650   Min.   :  45000  
 Class :character   1st Qu.:0.0000   1st Qu.:108000   1st Qu.: 270000  
 Mode  :character   Median :0.0000   Median :135000   Median : 491031  
                    Mean   :0.3625   Mean   :148333   Mean   : 567430  
                    3rd Qu.:1.0000   3rd Qu.:180000   3rd Qu.: 781695  
                    Max.   :3.0000   Max.   :299700   Max.   :3860019  
  AMT_ANNUITY     AMT_GOODS_PRICE   NAME_TYPE_SUITE    NAME_INCOME_TYPE  
 Min.   :  1616   Min.   :  40500   Length:237776      Length:237776     
 1st Qu.: 16006   1st Qu.: 229500   Class :character   Class :character  
 Median : 23837   Median : 450000   Mode  :character   Mode  :character  
 Mean   : 25678   Mean   : 509126                                        
 3rd Qu.: 32603   3rd Qu.: 675000                                        
 Max.   :225000   Max.   :3555000                                        
 NAME_EDUCATION_TYPE NAME_FAMILY_STATUS NAME_HOUSING_TYPE 
 Length:237776       Length:237776      Length:237776     
 Class :character    Class :character   Class :character  
 Mode  :character    Mode  :character   Mode  :character  
                                                          
                                                          
                                                          
 REGION_POPULATION_RELATIVE   DAYS_BIRTH    DAYS_REGISTRATION DAYS_ID_PUBLISH
 Min.   :0.00029            Min.   : 7673   Min.   :    0     Min.   :   0   
 1st Qu.:0.01001            1st Qu.:12439   1st Qu.: 2108     1st Qu.:1721   
 Median :0.01885            Median :15968   Median : 4601     Median :3262   
 Mean   :0.02044            Mean   :16187   Mean   : 5097     Mean   :2996   
 3rd Qu.:0.02639            3rd Qu.:19961   3rd Qu.: 7649     3rd Qu.:4299   
 Max.   :0.07251            Max.   :25201   Max.   :24672     Max.   :7197   
  OWN_CAR_AGE   FLAG_EMP_PHONE FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL
 Min.   : 0.0   0: 47432       0:190061        0:170246   0:225462  
 1st Qu.: 0.0   1:190344       1: 47715        1: 67530   1: 12314  
 Median : 0.0                                                       
 Mean   : 1.4                                                       
 3rd Qu.: 0.0                                                       
 Max.   :12.0                                                       
 OCCUPATION_TYPE    CNT_FAM_MEMBERS REGION_RATING_CLIENT
 Length:237776      Min.   :1.00    1: 21787            
 Class :character   1st Qu.:2.00    2:179447            
 Mode  :character   Median :2.00    3: 36542            
                    Mean   :2.08                        
                    3rd Qu.:2.00                        
                    Max.   :4.00                        
 REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START HOUR_APPR_PROCESS_START
 1: 23152                    Length:237776              Min.   : 0.00          
 2:181331                    Class :character           1st Qu.:10.00          
 3: 33293                    Mode  :character           Median :12.00          
                                                        Mean   :12.09          
                                                        3rd Qu.:14.00          
                                                        Max.   :23.00          
 REG_REGION_NOT_WORK_REGION REG_CITY_NOT_LIVE_CITY REG_CITY_NOT_WORK_CITY
 0:227280                   0:219288               0:185117              
 1: 10496                   1: 18488               1: 52659              
                                                                         
                                                                         
                                                                         
                                                                         
 LIVE_CITY_NOT_WORK_CITY ORGANIZATION_TYPE   EXT_SOURCE_1   
 0:197449                Length:237776      Min.   :0.0000  
 1: 40327                Class :character   1st Qu.:0.0000  
                         Mode  :character   Median :0.0000  
                                            Mean   :0.2163  
                                            3rd Qu.:0.4528  
                                            Max.   :0.9516  
  EXT_SOURCE_2        EXT_SOURCE_3       APARTMENTS_MEDI   YEARS_BUILD_MEDI
 Min.   :0.0000001   Min.   :0.0005273   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.3859750   1st Qu.:0.3706496   1st Qu.:0.03440   1st Qu.:0.6578  
 Median :0.5627356   Median :0.5388627   Median :0.07290   Median :0.7048  
 Mean   :0.5111018   Mean   :0.5118501   Mean   :0.09919   Mean   :0.7177  
 3rd Qu.:0.6612173   3rd Qu.:0.6690567   3rd Qu.:0.12280   3rd Qu.:0.7920  
 Max.   :0.8549997   Max.   :0.8960095   Max.   :1.00000   Max.   :1.0000  
 COMMONAREA_MEDI   ELEVATORS_MEDI    ENTRANCES_MEDI   FLOORSMAX_MEDI  
 Min.   :0.00000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.00590   1st Qu.:0.00000   1st Qu.:0.0345   1st Qu.:0.1667  
 Median :0.01620   Median :0.00000   Median :0.1034   Median :0.1667  
 Mean   :0.03946   Mean   :0.07234   Mean   :0.1213   Mean   :0.2130  
 3rd Qu.:0.04580   3rd Qu.:0.12000   3rd Qu.:0.1379   3rd Qu.:0.3333  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
 FLOORSMIN_MEDI   LIVINGAPARTMENTS_MEDI LIVINGAREA_MEDI 
 Min.   :0.0000   Min.   :0.00000       Min.   :0.0000  
 1st Qu.:0.0833   1st Qu.:0.02740       1st Qu.:0.0388  
 Median :0.2083   Median :0.06070       Median :0.0677  
 Mean   :0.2207   Mean   :0.08435       Mean   :0.1003  
 3rd Qu.:0.3750   3rd Qu.:0.10180       3rd Qu.:0.1209  
 Max.   :1.0000   Max.   :1.00000       Max.   :1.0000  
 NONLIVINGAPARTMENTS_MEDI OBS_30_CNT_SOCIAL_CIRCLE DEF_30_CNT_SOCIAL_CIRCLE
 Min.   :0.00000          Min.   : 0.000           Min.   :0.0000          
 1st Qu.:0.00000          1st Qu.: 0.000           1st Qu.:0.0000          
 Median :0.00000          Median : 0.000           Median :0.0000          
 Mean   :0.00639          Mean   : 1.322           Mean   :0.1432          
 3rd Qu.:0.00000          3rd Qu.: 2.000           3rd Qu.:0.0000          
 Max.   :1.00000          Max.   :10.000           Max.   :6.0000          
 OBS_60_CNT_SOCIAL_CIRCLE DEF_60_CNT_SOCIAL_CIRCLE DAYS_LAST_PHONE_CHANGE
 Min.   : 0.000           Min.   :0.0000           Min.   :   0.0        
 1st Qu.: 0.000           1st Qu.:0.0000           1st Qu.: 266.0        
 Median : 0.000           Median :0.0000           Median : 741.0        
 Mean   : 1.306           Mean   :0.1005           Mean   : 949.7        
 3rd Qu.: 2.000           3rd Qu.:0.0000           3rd Qu.:1554.0        
 Max.   :10.000           Max.   :6.0000           Max.   :4292.0        
 FLAG_DOCUMENT_3 FLAG_DOCUMENT_6 FLAG_DOCUMENT_8 AMT_REQ_CREDIT_BUREAU_HOUR
 0: 66846        0:214506        0:222941        Min.   :0.000000          
 1:170930        1: 23270        1: 14835        1st Qu.:0.000000          
                                                 Median :0.000000          
                                                 Mean   :0.005451          
                                                 3rd Qu.:0.000000          
                                                 Max.   :4.000000          
 AMT_REQ_CREDIT_BUREAU_DAY AMT_REQ_CREDIT_BUREAU_WEEK AMT_REQ_CREDIT_BUREAU_MON
 Min.   :0.000000          Min.   :0.00000            Min.   : 0.0000          
 1st Qu.:0.000000          1st Qu.:0.00000            1st Qu.: 0.0000          
 Median :0.000000          Median :0.00000            Median : 0.0000          
 Mean   :0.006157          Mean   :0.02947            Mean   : 0.2221          
 3rd Qu.:0.000000          3rd Qu.:0.00000            3rd Qu.: 0.0000          
 Max.   :9.000000          Max.   :8.00000            Max.   :24.0000          
 AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
 Min.   : 0.00             Min.   : 0.00             
 1st Qu.: 0.00             1st Qu.: 1.00             
 Median : 0.00             Median : 1.00             
 Mean   : 0.23             Mean   : 1.78             
 3rd Qu.: 0.00             3rd Qu.: 3.00             
 Max.   :19.00             Max.   :25.00             
 House_Attribute_Low_Variance
 Min.   :-2.77162            
 1st Qu.:-0.52169            
 Median :-0.52169            
 Mean   :-0.00629            
 3rd Qu.:-0.34387            
 Max.   :53.15290            </code></pre>
</div>
</div>
</section>
<section id="clean-test-data" class="level2">
<h2 class="anchored" data-anchor-id="clean-test-data">Clean Test Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modify all character variables into factors</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>te_clean <span class="ot">&lt;-</span> test_clean <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate_if</span>(is.character, as.factor)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Store all numeric variables which should be factors in a vector</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>num_cat_values2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"FLAG_EMP_PHONE"</span>,<span class="st">"FLAG_WORK_PHONE"</span>,<span class="st">"FLAG_EMAIL"</span>,<span class="st">"FLAG_PHONE"</span>,<span class="st">'REG_REGION_NOT_WORK_REGION'</span>,<span class="st">'LIVE_CITY_NOT_WORK_CITY'</span>,<span class="st">"REG_CITY_NOT_LIVE_CITY"</span>,<span class="st">"REG_CITY_NOT_WORK_CITY"</span>,<span class="st">"REGION_RATING_CLIENT_W_CITY"</span>,<span class="st">"FLAG_DOCUMENT_3"</span>,<span class="st">"FLAG_DOCUMENT_6"</span>,<span class="st">"FLAG_DOCUMENT_8"</span>,<span class="st">"REGION_RATING_CLIENT"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># transform the vector of num. columns to factors</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>te_clean <span class="ot">&lt;-</span> test_clean <span class="sc">%&gt;%</span> </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(num_cat_values2), as.factor))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of cleaned dataset</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(te_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   SK_ID_CURR     NAME_CONTRACT_TYPE CODE_GENDER        FLAG_OWN_CAR      
 Min.   :100001   Length:37740       Length:37740       Length:37740      
 1st Qu.:186702   Class :character   Class :character   Class :character  
 Median :275020   Mode  :character   Mode  :character   Mode  :character  
 Mean   :274808                                                           
 3rd Qu.:362886                                                           
 Max.   :450458                                                           
 FLAG_OWN_REALTY     CNT_CHILDREN    AMT_INCOME_TOTAL   AMT_CREDIT     
 Length:37740       Min.   :0.0000   Min.   : 26942   Min.   :  45000  
 Class :character   1st Qu.:0.0000   1st Qu.:112500   1st Qu.: 248760  
 Mode  :character   Median :0.0000   Median :153000   Median : 414612  
                    Mean   :0.3456   Mean   :155613   Mean   : 480048  
                    3rd Qu.:1.0000   3rd Qu.:202500   3rd Qu.: 610484  
                    Max.   :3.0000   Max.   :299250   Max.   :2245500  
  AMT_ANNUITY     AMT_GOODS_PRICE   NAME_TYPE_SUITE    NAME_INCOME_TYPE  
 Min.   :  2295   Min.   :  45000   Length:37740       Length:37740      
 1st Qu.: 17262   1st Qu.: 225000   Class :character   Class :character  
 Median : 24926   Median : 360000   Mode  :character   Mode  :character  
 Mean   : 27570   Mean   : 428636                                        
 3rd Qu.: 34826   3rd Qu.: 540000                                        
 Max.   :177827   Max.   :2245500                                        
 NAME_EDUCATION_TYPE NAME_FAMILY_STATUS NAME_HOUSING_TYPE 
 Length:37740        Length:37740       Length:37740      
 Class :character    Class :character   Class :character  
 Mode  :character    Mode  :character   Mode  :character  
                                                          
                                                          
                                                          
 REGION_POPULATION_RELATIVE   DAYS_BIRTH    DAYS_REGISTRATION DAYS_ID_PUBLISH
 Min.   :0.000253           Min.   : 7338   Min.   :    0     Min.   :   0   
 1st Qu.:0.010006           1st Qu.:12503   1st Qu.: 2004     1st Qu.:1711   
 Median :0.018850           Median :16004   Median : 4622     Median :3249   
 Mean   :0.020619           Mean   :16211   Mean   : 5092     Mean   :3058   
 3rd Qu.:0.028663           3rd Qu.:19942   3rd Qu.: 7659     3rd Qu.:4448   
 Max.   :0.072508           Max.   :25195   Max.   :23722     Max.   :6348   
  OWN_CAR_AGE     FLAG_EMP_PHONE FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL
 Min.   : 0.000   0: 7997        0:30036         0:27716    0:31937   
 1st Qu.: 0.000   1:29743        1: 7704         1:10024    1: 5803   
 Median : 0.000                                                       
 Mean   : 1.403                                                       
 3rd Qu.: 0.000                                                       
 Max.   :12.000                                                       
 OCCUPATION_TYPE    CNT_FAM_MEMBERS REGION_RATING_CLIENT
 Length:37740       Min.   :1.000   1: 3787             
 Class :character   1st Qu.:2.000   2:28156             
 Mode  :character   Median :2.000   3: 5797             
                    Mean   :2.077                       
                    3rd Qu.:2.000                       
                    Max.   :4.000                       
 REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START HOUR_APPR_PROCESS_START
 -1:    1                    Length:37740               Min.   : 0.00          
 1 : 4059                    Class :character           1st Qu.:10.00          
 2 :28464                    Mode  :character           Median :12.00          
 3 : 5216                                               Mean   :12.04          
                                                        3rd Qu.:14.00          
                                                        Max.   :23.00          
 REG_REGION_NOT_WORK_REGION REG_CITY_NOT_LIVE_CITY REG_CITY_NOT_WORK_CITY
 0:35988                    0:34829                0:29659               
 1: 1752                    1: 2911                1: 8081               
                                                                         
                                                                         
                                                                         
                                                                         
 LIVE_CITY_NOT_WORK_CITY ORGANIZATION_TYPE   EXT_SOURCE_1   
 0:31586                 Length:37740       Min.   :0.0000  
 1: 6154                 Class :character   1st Qu.:0.0000  
                         Mode  :character   Median :0.2366  
                                            Mean   :0.2853  
                                            3rd Qu.:0.5464  
                                            Max.   :0.9391  
  EXT_SOURCE_2        EXT_SOURCE_3       APARTMENTS_MEDI  YEARS_BUILD_MEDI
 Min.   :0.0000081   Min.   :0.0005273   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.4039882   1st Qu.:0.3656165   1st Qu.:0.0416   1st Qu.:0.6847  
 Median :0.5556799   Median :0.5208976   Median :0.0833   Median :0.7048  
 Mean   :0.5149308   Mean   :0.5020387   Mean   :0.1109   Mean   :0.7486  
 3rd Qu.:0.6555860   3rd Qu.:0.6545293   3rd Qu.:0.1374   3rd Qu.:0.8390  
 Max.   :0.8549997   Max.   :0.8825303   Max.   :1.0000   Max.   :1.0000  
 COMMONAREA_MEDI   ELEVATORS_MEDI    ENTRANCES_MEDI   FLOORSMAX_MEDI  
 Min.   :0.00000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.00760   1st Qu.:0.00000   1st Qu.:0.0690   1st Qu.:0.1667  
 Median :0.02200   Median :0.00000   Median :0.1379   Median :0.1667  
 Mean   :0.05325   Mean   :0.08353   Mean   :0.1438   Mean   :0.2270  
 3rd Qu.:0.05750   3rd Qu.:0.12000   3rd Qu.:0.2069   3rd Qu.:0.3333  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
 FLOORSMIN_MEDI   LIVINGAPARTMENTS_MEDI LIVINGAREA_MEDI 
 Min.   :0.0000   Min.   :0.00000       Min.   :0.0000  
 1st Qu.:0.0833   1st Qu.:0.03850       1st Qu.:0.0488  
 Median :0.2083   Median :0.06670       Median :0.0771  
 Mean   :0.2255   Mean   :0.09857       Mean   :0.1115  
 3rd Qu.:0.3750   3rd Qu.:0.12310       3rd Qu.:0.1359  
 Max.   :1.0000   Max.   :1.00000       Max.   :1.0000  
 NONLIVINGAPARTMENTS_MEDI OBS_30_CNT_SOCIAL_CIRCLE DEF_30_CNT_SOCIAL_CIRCLE
 Min.   :0.000000         Min.   : 0.000           Min.   :0.0000          
 1st Qu.:0.000000         1st Qu.: 0.000           1st Qu.:0.0000          
 Median :0.000000         Median : 0.000           Median :0.0000          
 Mean   :0.008813         Mean   : 1.332           Mean   :0.1427          
 3rd Qu.:0.003900         3rd Qu.: 2.000           3rd Qu.:0.0000          
 Max.   :1.000000         Max.   :10.000           Max.   :6.0000          
 OBS_60_CNT_SOCIAL_CIRCLE DEF_60_CNT_SOCIAL_CIRCLE DAYS_LAST_PHONE_CHANGE
 Min.   : 0.000           Min.   :0.0000           Min.   :   0          
 1st Qu.: 0.000           1st Qu.:0.0000           1st Qu.: 354          
 Median : 0.000           Median :0.0000           Median : 839          
 Mean   : 1.321           Mean   :0.1015           Mean   :1062          
 3rd Qu.: 2.000           3rd Qu.:0.0000           3rd Qu.:1755          
 Max.   :10.000           Max.   :5.0000           Max.   :4361          
 FLAG_DOCUMENT_3 FLAG_DOCUMENT_6 FLAG_DOCUMENT_8 AMT_REQ_CREDIT_BUREAU_HOUR
 0: 7685         0:34055         0:35182         Min.   :0.000000          
 1:30055         1: 3685         1: 2558         1st Qu.:0.000000          
                                                 Median :0.000000          
                                                 Mean   :0.001696          
                                                 3rd Qu.:0.000000          
                                                 Max.   :1.000000          
 AMT_REQ_CREDIT_BUREAU_DAY AMT_REQ_CREDIT_BUREAU_WEEK AMT_REQ_CREDIT_BUREAU_MON
 Min.   :0.000000          Min.   :0.000000           Min.   :0.000000         
 1st Qu.:0.000000          1st Qu.:0.000000           1st Qu.:0.000000         
 Median :0.000000          Median :0.000000           Median :0.000000         
 Mean   :0.001431          Mean   :0.002544           Mean   :0.008161         
 3rd Qu.:0.000000          3rd Qu.:0.000000           3rd Qu.:0.000000         
 Max.   :2.000000          Max.   :2.000000           Max.   :6.000000         
 AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
 Min.   :0.0000            Min.   : 0.000            
 1st Qu.:0.0000            1st Qu.: 1.000            
 Median :0.0000            Median : 2.000            
 Mean   :0.4734            Mean   : 1.999            
 3rd Qu.:1.0000            3rd Qu.: 3.000            
 Max.   :7.0000            Max.   :17.000            
 House_Attribute_Low_Variance
 Min.   :-2.78776            
 1st Qu.:-0.53249            
 Median :-0.53249            
 Mean   :-0.00739            
 3rd Qu.:-0.29941            
 Max.   :48.18664            </code></pre>
</div>
</div>
</section>
</section>
<section id="class-imbalance" class="level1">
<h1>Class Imbalance</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tr_clean<span class="sc">$</span>TARGET)  <span class="co">#class distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
218531  19245 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(tr_clean<span class="sc">$</span>TARGET)),<span class="dv">4</span>) <span class="sc">*</span> <span class="dv">100</span>  <span class="co">#percentages</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
91.91  8.09 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot to show class imbalance</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tr_clean, <span class="fu">aes</span>(<span class="at">x =</span>TARGET, <span class="at">fill =</span>TARGET)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"skyblue"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"tomato"</span>)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Class Imbalance in Home Credit Default Risk Dataset"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Default Status"</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Default Status"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelling_nikita_pdf_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows there’s a huge class imbalance and majority of the clients have re-payed the loan. 91.91% of them show successful repayment and our models have a lot to learn from this information.</p>
</section>
<section id="non-linear-separability-check" class="level1">
<h1>Non-Linear Separability Check</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select any 2 random numeric variables and check scatter plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>tr_clean<span class="sc">|&gt;</span> <span class="co"># use cleaned initial train data before split (as train_matrix doesn't contain target)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> AMT_INCOME_TOTAL, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">y =</span> AMT_CREDIT, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="fu">as.factor</span>(TARGET))) <span class="sc">+</span>  <span class="co"># set color as TARGET</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter Plot of Client Income vs Loan Credit Amount"</span>, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Total Income"</span>, <span class="co"># custom x-axis</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Credit Amount"</span>, <span class="co"># custom y -axis</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Default Status"</span>) <span class="sc">+</span>  <span class="co"># Add a label for the color legend</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"green"</span>),  </span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Default"</span>, <span class="st">"Defaulted"</span>)) <span class="sc">+</span>  </span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelling_nikita_pdf_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We have randomly selected 2 numeric variables from the cleaned dataset and plotted the relationship between them filtered by default status. It is clearly seen there is a class overlap and the data is noisy. The relationships are complex and cannot be separated by a straight line, we hence implement the XGboost blackbox model to capture such patterns along with improved performance and bias.</p>
<p>We can also cross verify this by modelling linear models such as SVM with a linear kernel or a simple logistic regression. The models would likely perform poorly, a model like the linear SVM would struggle by taking a long training time and using many vectors to make the predictions which indicates non-linear data.</p>
</section>
<section id="data-split" class="level1">
<h1>Data Split</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure TARGET is a factor</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#str(tr_clean$TARGET)</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into training and validation sets</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(tr_clean<span class="sc">$</span>TARGET, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> tr_clean[train_index, ]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> tr_clean[<span class="sc">-</span>train_index, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="logistic-regression-performance" class="level1">
<h1>Logistic Regression Performance</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit glm model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(TARGET<span class="sc">~</span>., <span class="at">data =</span> train_data, <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = TARGET ~ ., family = binomial(), data = train_data)

Coefficients: (1 not defined because of singularities)
                                                   Estimate Std. Error z value
(Intercept)                                      -3.213e+01  3.969e+02  -0.081
NAME_CONTRACT_TYPERevolving loans                -7.497e-02  6.326e-02  -1.185
CODE_GENDERM                                      3.375e-01  2.495e-02  13.529
FLAG_OWN_CARY                                    -4.633e-01  4.829e-02  -9.594
FLAG_OWN_REALTYY                                  1.954e-02  2.135e-02   0.915
CNT_CHILDREN                                      2.960e-02  1.569e-02   1.887
AMT_INCOME_TOTAL                                 -4.992e-08  2.036e-07  -0.245
AMT_CREDIT                                        2.141e-06  1.568e-07  13.657
AMT_ANNUITY                                       1.203e-05  1.239e-06   9.707
AMT_GOODS_PRICE                                  -2.665e-06  1.787e-07 -14.912
NAME_TYPE_SUITEFamily                            -4.353e-03  9.629e-02  -0.045
NAME_TYPE_SUITEGroup of people                    2.024e-01  3.085e-01   0.656
NAME_TYPE_SUITEOther_A                           -6.387e-02  1.926e-01  -0.332
NAME_TYPE_SUITEOther_B                            5.848e-02  1.461e-01   0.400
NAME_TYPE_SUITESpouse, partner                   -1.064e-01  1.056e-01  -1.007
NAME_TYPE_SUITEUnaccompanied                     -4.463e-03  9.322e-02  -0.048
NAME_INCOME_TYPECommercial associate              1.048e+01  3.017e+02   0.035
NAME_INCOME_TYPEMaternity leave                   1.388e+01  3.017e+02   0.046
NAME_INCOME_TYPEPensioner                        -2.327e-01  3.692e+02  -0.001
NAME_INCOME_TYPEState servant                     1.049e+01  3.017e+02   0.035
NAME_INCOME_TYPEStudent                          -5.952e-01  3.327e+02  -0.002
NAME_INCOME_TYPEUnemployed                        2.973e+00  3.692e+02   0.008
NAME_INCOME_TYPEWorking                           1.059e+01  3.017e+02   0.035
NAME_EDUCATION_TYPEHigher education               1.070e+01  6.165e+01   0.174
NAME_EDUCATION_TYPEIncomplete higher              1.077e+01  6.165e+01   0.175
NAME_EDUCATION_TYPELower secondary                1.102e+01  6.165e+01   0.179
NAME_EDUCATION_TYPESecondary / secondary special  1.094e+01  6.165e+01   0.177
NAME_FAMILY_STATUSMarried                        -1.322e-01  3.046e-02  -4.338
NAME_FAMILY_STATUSSeparated                       4.853e-02  4.526e-02   1.072
NAME_FAMILY_STATUSSingle / not married           -5.443e-02  3.566e-02  -1.526
NAME_FAMILY_STATUSUnknown                        -1.013e+01  5.354e+02  -0.019
NAME_FAMILY_STATUSWidow                          -8.499e-02  5.350e-02  -1.588
NAME_HOUSING_TYPEHouse / apartment                1.033e-01  1.711e-01   0.604
NAME_HOUSING_TYPEMunicipal apartment              1.752e-01  1.777e-01   0.986
NAME_HOUSING_TYPEOffice apartment                -8.875e-02  2.041e-01  -0.435
NAME_HOUSING_TYPERented apartment                 2.583e-01  1.812e-01   1.426
NAME_HOUSING_TYPEWith parents                     1.321e-01  1.745e-01   0.757
REGION_POPULATION_RELATIVE                        2.760e+00  9.695e-01   2.847
DAYS_BIRTH                                       -2.790e-05  3.250e-06  -8.586
DAYS_REGISTRATION                                -1.109e-05  2.966e-06  -3.739
DAYS_ID_PUBLISH                                  -5.185e-05  6.677e-06  -7.765
OWN_CAR_AGE                                       2.103e-02  6.190e-03   3.397
FLAG_EMP_PHONE1                                   1.052e+01  2.505e+02   0.042
FLAG_WORK_PHONE1                                  1.934e-01  2.486e-02   7.780
FLAG_PHONE1                                      -9.585e-02  2.316e-02  -4.138
FLAG_EMAIL1                                       1.567e-02  4.307e-02   0.364
OCCUPATION_TYPECleaning staff                     2.609e-01  9.389e-02   2.779
OCCUPATION_TYPECooking staff                      1.601e-01  8.858e-02   1.808
OCCUPATION_TYPECore staff                         1.505e-02  7.541e-02   0.200
OCCUPATION_TYPEDrivers                            2.396e-01  7.884e-02   3.039
OCCUPATION_TYPEHigh skill tech staff              7.016e-02  8.442e-02   0.831
OCCUPATION_TYPEHR staff                           4.174e-01  2.266e-01   1.842
OCCUPATION_TYPEIT staff                          -4.723e-02  2.921e-01  -0.162
OCCUPATION_TYPELaborers                           2.054e-01  6.998e-02   2.935
OCCUPATION_TYPELow-skill Laborers                 3.284e-01  1.074e-01   3.057
OCCUPATION_TYPEManagers                           3.775e-02  7.961e-02   0.474
OCCUPATION_TYPEMedicine staff                     3.623e-02  9.891e-02   0.366
OCCUPATION_TYPEPrivate service staff              1.441e-02  1.282e-01   0.112
OCCUPATION_TYPERealty agents                     -9.831e-02  2.163e-01  -0.454
OCCUPATION_TYPESales staff                        1.299e-01  7.143e-02   1.819
OCCUPATION_TYPESecretaries                        1.644e-01  1.620e-01   1.015
OCCUPATION_TYPESecurity staff                     2.441e-01  9.652e-02   2.529
OCCUPATION_TYPEUnemployed                         1.297e-01  7.021e-02   1.847
OCCUPATION_TYPEWaiters/barmen staff               2.721e-01  1.328e-01   2.048
CNT_FAM_MEMBERS                                          NA         NA      NA
REGION_RATING_CLIENT2                            -3.482e-01  1.622e-01  -2.147
REGION_RATING_CLIENT3                            -2.490e-01  1.638e-01  -1.520
REGION_RATING_CLIENT_W_CITY2                      4.999e-01  1.548e-01   3.229
REGION_RATING_CLIENT_W_CITY3                      5.553e-01  1.580e-01   3.514
WEEKDAY_APPR_PROCESS_STARTMONDAY                 -8.573e-02  3.285e-02  -2.610
WEEKDAY_APPR_PROCESS_STARTSATURDAY               -6.681e-02  3.652e-02  -1.830
WEEKDAY_APPR_PROCESS_STARTSUNDAY                 -1.110e-01  4.741e-02  -2.341
WEEKDAY_APPR_PROCESS_STARTTHURSDAY               -3.796e-02  3.257e-02  -1.166
WEEKDAY_APPR_PROCESS_STARTTUESDAY                 2.076e-02  3.171e-02   0.655
WEEKDAY_APPR_PROCESS_STARTWEDNESDAY              -9.614e-03  3.221e-02  -0.298
HOUR_APPR_PROCESS_START                           6.945e-04  3.068e-03   0.226
REG_REGION_NOT_WORK_REGION1                      -7.786e-02  4.614e-02  -1.688
REG_CITY_NOT_LIVE_CITY1                           1.861e-01  4.670e-02   3.986
REG_CITY_NOT_WORK_CITY1                          -2.391e-03  5.219e-02  -0.046
LIVE_CITY_NOT_WORK_CITY1                          3.323e-02  5.054e-02   0.658
ORGANIZATION_TYPEAgriculture                     -2.935e-01  2.628e-01  -1.117
ORGANIZATION_TYPEBank                            -4.943e-01  2.730e-01  -1.811
ORGANIZATION_TYPEBusiness Entity Type 1          -3.538e-01  2.532e-01  -1.397
ORGANIZATION_TYPEBusiness Entity Type 2          -3.117e-01  2.489e-01  -1.252
ORGANIZATION_TYPEBusiness Entity Type 3          -1.771e-01  2.445e-01  -0.724
ORGANIZATION_TYPECleaning                         1.500e-02  3.579e-01   0.042
ORGANIZATION_TYPEConstruction                    -5.584e-02  2.508e-01  -0.223
ORGANIZATION_TYPECulture                         -7.263e-02  3.625e-01  -0.200
ORGANIZATION_TYPEElectricity                     -3.759e-01  3.034e-01  -1.239
ORGANIZATION_TYPEEmergency                       -3.099e-01  3.398e-01  -0.912
ORGANIZATION_TYPEGovernment                      -3.314e-01  2.498e-01  -1.326
ORGANIZATION_TYPEHotel                           -4.523e-01  2.984e-01  -1.516
ORGANIZATION_TYPEHousing                         -4.194e-01  2.639e-01  -1.589
ORGANIZATION_TYPEIndustry: type 1                -1.198e-01  2.810e-01  -0.426
ORGANIZATION_TYPEIndustry: type 10               -2.031e-01  5.569e-01  -0.365
ORGANIZATION_TYPEIndustry: type 11               -2.816e-01  2.621e-01  -1.074
ORGANIZATION_TYPEIndustry: type 12               -8.838e-01  4.611e-01  -1.917
ORGANIZATION_TYPEIndustry: type 13               -2.529e-01  5.698e-01  -0.444
ORGANIZATION_TYPEIndustry: type 2                -5.986e-01  3.482e-01  -1.719
ORGANIZATION_TYPEIndustry: type 3                -1.463e-01  2.570e-01  -0.570
ORGANIZATION_TYPEIndustry: type 4                -1.903e-01  2.867e-01  -0.664
ORGANIZATION_TYPEIndustry: type 5                -4.307e-01  3.197e-01  -1.347
ORGANIZATION_TYPEIndustry: type 6                -1.044e+00  7.728e-01  -1.351
ORGANIZATION_TYPEIndustry: type 7                -3.597e-01  2.816e-01  -1.277
ORGANIZATION_TYPEIndustry: type 8                -4.583e-01  1.077e+00  -0.425
ORGANIZATION_TYPEIndustry: type 9                -6.141e-01  2.666e-01  -2.303
ORGANIZATION_TYPEInsurance                       -4.141e-01  3.641e-01  -1.137
ORGANIZATION_TYPEKindergarten                    -2.604e-01  2.525e-01  -1.031
ORGANIZATION_TYPELegal Services                   2.940e-01  3.974e-01   0.740
ORGANIZATION_TYPEMedicine                        -2.872e-01  2.525e-01  -1.137
ORGANIZATION_TYPEMilitary                        -7.424e-01  2.776e-01  -2.675
ORGANIZATION_TYPEMobile                          -1.855e-01  3.784e-01  -0.490
ORGANIZATION_TYPEOther                           -3.066e-01  2.474e-01  -1.239
ORGANIZATION_TYPEPolice                          -6.397e-01  2.813e-01  -2.274
ORGANIZATION_TYPEPostal                          -1.588e-01  2.658e-01  -0.597
ORGANIZATION_TYPERealtor                          5.412e-01  3.431e-01   1.577
ORGANIZATION_TYPEReligion                         2.584e-01  5.467e-01   0.473
ORGANIZATION_TYPERestaurant                      -6.858e-02  2.644e-01  -0.259
ORGANIZATION_TYPESchool                          -4.187e-01  2.517e-01  -1.663
ORGANIZATION_TYPESecurity                        -3.232e-01  2.646e-01  -1.222
ORGANIZATION_TYPESecurity Ministries             -5.352e-01  2.844e-01  -1.882
ORGANIZATION_TYPESelf-employed                   -9.029e-02  2.451e-01  -0.368
ORGANIZATION_TYPEServices                        -1.618e-01  2.822e-01  -0.573
ORGANIZATION_TYPETelecom                         -2.906e-01  3.303e-01  -0.880
ORGANIZATION_TYPETrade: type 1                   -7.032e-02  3.425e-01  -0.205
ORGANIZATION_TYPETrade: type 2                   -6.417e-01  2.758e-01  -2.327
ORGANIZATION_TYPETrade: type 3                   -1.041e-01  2.561e-01  -0.407
ORGANIZATION_TYPETrade: type 4                   -1.505e+00  1.072e+00  -1.404
ORGANIZATION_TYPETrade: type 5                   -1.123e+01  9.562e+01  -0.117
ORGANIZATION_TYPETrade: type 6                   -5.597e-01  3.575e-01  -1.565
ORGANIZATION_TYPETrade: type 7                   -1.348e-01  2.500e-01  -0.539
ORGANIZATION_TYPETransport: type 1               -1.631e+00  7.618e-01  -2.141
ORGANIZATION_TYPETransport: type 2               -3.182e-01  2.689e-01  -1.183
ORGANIZATION_TYPETransport: type 3                5.851e-01  2.706e-01   2.162
ORGANIZATION_TYPETransport: type 4               -2.007e-01  2.535e-01  -0.792
ORGANIZATION_TYPEUnemployed                       2.101e+01  3.287e+02   0.064
ORGANIZATION_TYPEUniversity                      -4.568e-01  3.006e-01  -1.519
EXT_SOURCE_1                                     -6.169e-01  4.050e-02 -15.232
EXT_SOURCE_2                                     -2.015e+00  4.851e-02 -41.526
EXT_SOURCE_3                                     -2.149e+00  4.754e-02 -45.197
APARTMENTS_MEDI                                  -4.082e-03  1.154e-01  -0.035
YEARS_BUILD_MEDI                                 -1.507e-01  9.518e-02  -1.584
COMMONAREA_MEDI                                   1.065e-01  1.393e-01   0.765
ELEVATORS_MEDI                                   -6.328e-02  9.660e-02  -0.655
ENTRANCES_MEDI                                   -1.401e-01  1.055e-01  -1.328
FLOORSMAX_MEDI                                   -1.572e-01  1.021e-01  -1.539
FLOORSMIN_MEDI                                    8.244e-02  6.845e-02   1.204
LIVINGAPARTMENTS_MEDI                             3.676e-02  1.100e-01   0.334
LIVINGAREA_MEDI                                   8.516e-02  1.124e-01   0.758
NONLIVINGAPARTMENTS_MEDI                         -3.982e-01  2.281e-01  -1.746
OBS_30_CNT_SOCIAL_CIRCLE                          5.179e-02  7.085e-02   0.731
DEF_30_CNT_SOCIAL_CIRCLE                          1.572e-01  3.875e-02   4.057
OBS_60_CNT_SOCIAL_CIRCLE                         -5.786e-02  7.158e-02  -0.808
DEF_60_CNT_SOCIAL_CIRCLE                          5.402e-02  4.556e-02   1.186
DAYS_LAST_PHONE_CHANGE                           -5.456e-05  1.283e-05  -4.254
FLAG_DOCUMENT_31                                  2.466e-01  5.526e-02   4.462
FLAG_DOCUMENT_61                                  1.624e-01  7.099e-02   2.288
FLAG_DOCUMENT_81                                 -3.124e-02  6.795e-02  -0.460
AMT_REQ_CREDIT_BUREAU_HOUR                       -6.843e-02  1.260e-01  -0.543
AMT_REQ_CREDIT_BUREAU_DAY                         1.206e-01  8.787e-02   1.373
AMT_REQ_CREDIT_BUREAU_WEEK                       -5.026e-02  5.126e-02  -0.980
AMT_REQ_CREDIT_BUREAU_MON                        -1.705e-02  1.372e-02  -1.242
AMT_REQ_CREDIT_BUREAU_QRT                        -2.840e-02  1.626e-02  -1.747
AMT_REQ_CREDIT_BUREAU_YEAR                        1.196e-02  5.361e-03   2.230
House_Attribute_Low_Variance                     -1.686e-02  6.295e-03  -2.678
                                                 Pr(&gt;|z|)    
(Intercept)                                      0.935477    
NAME_CONTRACT_TYPERevolving loans                0.235919    
CODE_GENDERM                                      &lt; 2e-16 ***
FLAG_OWN_CARY                                     &lt; 2e-16 ***
FLAG_OWN_REALTYY                                 0.360203    
CNT_CHILDREN                                     0.059103 .  
AMT_INCOME_TOTAL                                 0.806348    
AMT_CREDIT                                        &lt; 2e-16 ***
AMT_ANNUITY                                       &lt; 2e-16 ***
AMT_GOODS_PRICE                                   &lt; 2e-16 ***
NAME_TYPE_SUITEFamily                            0.963938    
NAME_TYPE_SUITEGroup of people                   0.511867    
NAME_TYPE_SUITEOther_A                           0.740244    
NAME_TYPE_SUITEOther_B                           0.688993    
NAME_TYPE_SUITESpouse, partner                   0.313820    
NAME_TYPE_SUITEUnaccompanied                     0.961813    
NAME_INCOME_TYPECommercial associate             0.972286    
NAME_INCOME_TYPEMaternity leave                  0.963305    
NAME_INCOME_TYPEPensioner                        0.999497    
NAME_INCOME_TYPEState servant                    0.972258    
NAME_INCOME_TYPEStudent                          0.998572    
NAME_INCOME_TYPEUnemployed                       0.993574    
NAME_INCOME_TYPEWorking                          0.971994    
NAME_EDUCATION_TYPEHigher education              0.862192    
NAME_EDUCATION_TYPEIncomplete higher             0.861346    
NAME_EDUCATION_TYPELower secondary               0.858148    
NAME_EDUCATION_TYPESecondary / secondary special 0.859204    
NAME_FAMILY_STATUSMarried                        1.44e-05 ***
NAME_FAMILY_STATUSSeparated                      0.283623    
NAME_FAMILY_STATUSSingle / not married           0.126921    
NAME_FAMILY_STATUSUnknown                        0.984904    
NAME_FAMILY_STATUSWidow                          0.112199    
NAME_HOUSING_TYPEHouse / apartment               0.546017    
NAME_HOUSING_TYPEMunicipal apartment             0.323923    
NAME_HOUSING_TYPEOffice apartment                0.663664    
NAME_HOUSING_TYPERented apartment                0.153906    
NAME_HOUSING_TYPEWith parents                    0.449076    
REGION_POPULATION_RELATIVE                       0.004417 ** 
DAYS_BIRTH                                        &lt; 2e-16 ***
DAYS_REGISTRATION                                0.000184 ***
DAYS_ID_PUBLISH                                  8.16e-15 ***
OWN_CAR_AGE                                      0.000681 ***
FLAG_EMP_PHONE1                                  0.966487    
FLAG_WORK_PHONE1                                 7.25e-15 ***
FLAG_PHONE1                                      3.50e-05 ***
FLAG_EMAIL1                                      0.715954    
OCCUPATION_TYPECleaning staff                    0.005453 ** 
OCCUPATION_TYPECooking staff                     0.070658 .  
OCCUPATION_TYPECore staff                        0.841827    
OCCUPATION_TYPEDrivers                           0.002376 ** 
OCCUPATION_TYPEHigh skill tech staff             0.405917    
OCCUPATION_TYPEHR staff                          0.065507 .  
OCCUPATION_TYPEIT staff                          0.871555    
OCCUPATION_TYPELaborers                          0.003337 ** 
OCCUPATION_TYPELow-skill Laborers                0.002234 ** 
OCCUPATION_TYPEManagers                          0.635358    
OCCUPATION_TYPEMedicine staff                    0.714150    
OCCUPATION_TYPEPrivate service staff             0.910532    
OCCUPATION_TYPERealty agents                     0.649500    
OCCUPATION_TYPESales staff                       0.068905 .  
OCCUPATION_TYPESecretaries                       0.309986    
OCCUPATION_TYPESecurity staff                    0.011424 *  
OCCUPATION_TYPEUnemployed                        0.064803 .  
OCCUPATION_TYPEWaiters/barmen staff              0.040528 *  
CNT_FAM_MEMBERS                                        NA    
REGION_RATING_CLIENT2                            0.031799 *  
REGION_RATING_CLIENT3                            0.128516    
REGION_RATING_CLIENT_W_CITY2                     0.001241 ** 
REGION_RATING_CLIENT_W_CITY3                     0.000442 ***
WEEKDAY_APPR_PROCESS_STARTMONDAY                 0.009064 ** 
WEEKDAY_APPR_PROCESS_STARTSATURDAY               0.067308 .  
WEEKDAY_APPR_PROCESS_STARTSUNDAY                 0.019231 *  
WEEKDAY_APPR_PROCESS_STARTTHURSDAY               0.243762    
WEEKDAY_APPR_PROCESS_STARTTUESDAY                0.512630    
WEEKDAY_APPR_PROCESS_STARTWEDNESDAY              0.765336    
HOUR_APPR_PROCESS_START                          0.820895    
REG_REGION_NOT_WORK_REGION1                      0.091505 .  
REG_CITY_NOT_LIVE_CITY1                          6.73e-05 ***
REG_CITY_NOT_WORK_CITY1                          0.963456    
LIVE_CITY_NOT_WORK_CITY1                         0.510802    
ORGANIZATION_TYPEAgriculture                     0.264040    
ORGANIZATION_TYPEBank                            0.070149 .  
ORGANIZATION_TYPEBusiness Entity Type 1          0.162385    
ORGANIZATION_TYPEBusiness Entity Type 2          0.210576    
ORGANIZATION_TYPEBusiness Entity Type 3          0.468992    
ORGANIZATION_TYPECleaning                        0.966556    
ORGANIZATION_TYPEConstruction                    0.823794    
ORGANIZATION_TYPECulture                         0.841194    
ORGANIZATION_TYPEElectricity                     0.215395    
ORGANIZATION_TYPEEmergency                       0.361776    
ORGANIZATION_TYPEGovernment                      0.184684    
ORGANIZATION_TYPEHotel                           0.129554    
ORGANIZATION_TYPEHousing                         0.111960    
ORGANIZATION_TYPEIndustry: type 1                0.669789    
ORGANIZATION_TYPEIndustry: type 10               0.715333    
ORGANIZATION_TYPEIndustry: type 11               0.282710    
ORGANIZATION_TYPEIndustry: type 12               0.055278 .  
ORGANIZATION_TYPEIndustry: type 13               0.657130    
ORGANIZATION_TYPEIndustry: type 2                0.085575 .  
ORGANIZATION_TYPEIndustry: type 3                0.568993    
ORGANIZATION_TYPEIndustry: type 4                0.506831    
ORGANIZATION_TYPEIndustry: type 5                0.177871    
ORGANIZATION_TYPEIndustry: type 6                0.176597    
ORGANIZATION_TYPEIndustry: type 7                0.201478    
ORGANIZATION_TYPEIndustry: type 8                0.670608    
ORGANIZATION_TYPEIndustry: type 9                0.021263 *  
ORGANIZATION_TYPEInsurance                       0.255464    
ORGANIZATION_TYPEKindergarten                    0.302459    
ORGANIZATION_TYPELegal Services                  0.459509    
ORGANIZATION_TYPEMedicine                        0.255454    
ORGANIZATION_TYPEMilitary                        0.007478 ** 
ORGANIZATION_TYPEMobile                          0.623972    
ORGANIZATION_TYPEOther                           0.215188    
ORGANIZATION_TYPEPolice                          0.022973 *  
ORGANIZATION_TYPEPostal                          0.550271    
ORGANIZATION_TYPERealtor                         0.114768    
ORGANIZATION_TYPEReligion                        0.636550    
ORGANIZATION_TYPERestaurant                      0.795332    
ORGANIZATION_TYPESchool                          0.096217 .  
ORGANIZATION_TYPESecurity                        0.221891    
ORGANIZATION_TYPESecurity Ministries             0.059868 .  
ORGANIZATION_TYPESelf-employed                   0.712593    
ORGANIZATION_TYPEServices                        0.566395    
ORGANIZATION_TYPETelecom                         0.379055    
ORGANIZATION_TYPETrade: type 1                   0.837323    
ORGANIZATION_TYPETrade: type 2                   0.019972 *  
ORGANIZATION_TYPETrade: type 3                   0.684347    
ORGANIZATION_TYPETrade: type 4                   0.160273    
ORGANIZATION_TYPETrade: type 5                   0.906499    
ORGANIZATION_TYPETrade: type 6                   0.117467    
ORGANIZATION_TYPETrade: type 7                   0.589750    
ORGANIZATION_TYPETransport: type 1               0.032257 *  
ORGANIZATION_TYPETransport: type 2               0.236671    
ORGANIZATION_TYPETransport: type 3               0.030586 *  
ORGANIZATION_TYPETransport: type 4               0.428435    
ORGANIZATION_TYPEUnemployed                      0.949029    
ORGANIZATION_TYPEUniversity                      0.128648    
EXT_SOURCE_1                                      &lt; 2e-16 ***
EXT_SOURCE_2                                      &lt; 2e-16 ***
EXT_SOURCE_3                                      &lt; 2e-16 ***
APARTMENTS_MEDI                                  0.971790    
YEARS_BUILD_MEDI                                 0.113291    
COMMONAREA_MEDI                                  0.444559    
ELEVATORS_MEDI                                   0.512398    
ENTRANCES_MEDI                                   0.184335    
FLOORSMAX_MEDI                                   0.123833    
FLOORSMIN_MEDI                                   0.228457    
LIVINGAPARTMENTS_MEDI                            0.738227    
LIVINGAREA_MEDI                                  0.448476    
NONLIVINGAPARTMENTS_MEDI                         0.080860 .  
OBS_30_CNT_SOCIAL_CIRCLE                         0.464746    
DEF_30_CNT_SOCIAL_CIRCLE                         4.97e-05 ***
OBS_60_CNT_SOCIAL_CIRCLE                         0.418945    
DEF_60_CNT_SOCIAL_CIRCLE                         0.235814    
DAYS_LAST_PHONE_CHANGE                           2.10e-05 ***
FLAG_DOCUMENT_31                                 8.10e-06 ***
FLAG_DOCUMENT_61                                 0.022158 *  
FLAG_DOCUMENT_81                                 0.645695    
AMT_REQ_CREDIT_BUREAU_HOUR                       0.587073    
AMT_REQ_CREDIT_BUREAU_DAY                        0.169888    
AMT_REQ_CREDIT_BUREAU_WEEK                       0.326845    
AMT_REQ_CREDIT_BUREAU_MON                        0.214147    
AMT_REQ_CREDIT_BUREAU_QRT                        0.080677 .  
AMT_REQ_CREDIT_BUREAU_YEAR                       0.025743 *  
House_Attribute_Low_Variance                     0.007411 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 93561  on 166443  degrees of freedom
Residual deviance: 83686  on 166280  degrees of freedom
AIC: 84014

Number of Fisher Scoring iterations: 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Predictions on the test data (probabilities)</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>test_pred_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(logistic, <span class="at">newdata =</span> test_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert probabilities to binary prediction outcomes using threshold = 0.5</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test_pred_probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluation</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate ROC-AUC</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_data<span class="sc">$</span>TARGET, test_pred_probs)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>roc_auc <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_obj)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"ROC-AUC:"</span>, <span class="fu">round</span>(roc_auc, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ROC-AUC: 0.7391 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Plot ROC Curve</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">FPR =</span> <span class="dv">1</span> <span class="sc">-</span> roc_obj<span class="sc">$</span>specificities,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">TPR =</span> roc_obj<span class="sc">$</span>sensitivities</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roc_curve, <span class="fu">aes</span>(<span class="at">x =</span> FPR, <span class="at">y =</span> TPR)) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"ROC Curve for Logistic Regression Model"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"1 - Specificity (FPR)"</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Sensitivity (TPR)"</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelling_nikita_pdf_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate accuracy</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test_predictions <span class="sc">==</span> test_data<span class="sc">$</span>TARGET)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Accuracy:"</span>, <span class="fu">round</span>(accuracy, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.919 </code></pre>
</div>
</div>
<p>The model shows high accuracy (91.91%) but this might be inflated due to an imbalanced dataset where non-defaults dominate. The AUC value of 73.91% suggests the model has acceptable discriminatory power in distinguishing between default and non-default cases, though there’s room for improvement.</p>
</section>
<section id="xgboost" class="level1">
<h1>XGBoost</h1>
<section id="define-model" class="level2">
<h2 class="anchored" data-anchor-id="define-model">Define Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dials)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doParallel)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust for class imbalance: calculate scale_pos_weight</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>scale_pos_weight <span class="ot">&lt;-</span> <span class="fu">sum</span>(train_data<span class="sc">$</span>TARGET <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(train_data<span class="sc">$</span>TARGET <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scale_pos_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.35481</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set scale_pos_weight as an option</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scale_pos_weight =</span> scale_pos_weight)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define XGBoost model</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>xgb_model <span class="ot">&lt;-</span> <span class="fu">boost_tree</span>(</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">trees =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tree_depth =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">learn_rate =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_size =</span> <span class="fu">tune</span>(),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">loss_reduction =</span> <span class="fu">tune</span>()</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"xgboost"</span>, </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">early_stopping_rounds =</span> <span class="dv">50</span>,  </span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">scale_pos_weight =</span> <span class="fu">getOption</span>(<span class="st">"scale_pos_weight"</span>),</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">tree_method =</span> <span class="st">"hist"</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">max_bin =</span> <span class="dv">256</span>,               </span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">nthread =</span> <span class="dv">4</span>,</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">verbosity =</span> <span class="dv">1</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="define-recipe" class="level3">
<h3 class="anchored" data-anchor-id="define-recipe">Define Recipe</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define Recipe</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(TARGET <span class="sc">~</span> ., <span class="at">data =</span> train_data) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_novel</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_other</span>(<span class="fu">all_nominal_predictors</span>(), <span class="at">threshold =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-grid-search-parameter-tuning-and-cv-function" class="level3">
<h3 class="anchored" data-anchor-id="define-grid-search-parameter-tuning-and-cv-function">Define Grid search parameter tuning and CV function</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define hyperparameter tuning grid</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>xgb_grid <span class="ot">&lt;-</span> <span class="fu">grid_random</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">trees</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>)),         <span class="co"># number of trees in each model</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tree_depth</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>)),       </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">learn_rate</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.2</span>)),  </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize</span>(<span class="fu">mtry</span>(), train_data),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">20</span>)),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_size =</span> <span class="fu">sample_prop</span>(<span class="fu">c</span>(<span class="fl">0.7</span>, <span class="dv">1</span>)),  <span class="co"># prop. of data in each node</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">loss_reduction</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">50</span>                          <span class="co"># 50 tree models</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Define 5-fold cross-validation</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>cv_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> TARGET)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="train-the-model" class="level2">
<h2 class="anchored" data-anchor-id="train-the-model">Train the Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Register parallel processing</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(doParallel)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>num_cores <span class="ot">&lt;-</span> <span class="fu">detectCores</span>()</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>num_cores</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(<span class="at">cores =</span> <span class="dv">4</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the workflow</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(xgb_model) <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(recipe)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune the model</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">metric_set</span>(yardstick<span class="sc">::</span>roc_auc, yardstick<span class="sc">::</span>mn_log_loss, yardstick<span class="sc">::</span>accuracy)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>xgb_tune_model <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  wf,</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> cv_folds,</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> xgb_grid,</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> metrics</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Stop parallel processing</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a><span class="fu">stopImplicitCluster</span>()</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="co">#show errors</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a><span class="co">#show_notes(xgb_tune_model)  </span></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="co">#collect_notes(xgb_tune_model)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="evaluate-model" class="level2">
<h2 class="anchored" data-anchor-id="evaluate-model">Evaluate Model</h2>
<section id="identify-best-hyperparameters-and-finalize-workflow" class="level3">
<h3 class="anchored" data-anchor-id="identify-best-hyperparameters-and-finalize-workflow">Identify best hyperparameters and finalize Workflow</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Collect fold-specific metrics</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>train_metrics <span class="ot">&lt;-</span> xgb_tune_model <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model Training Performance:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Training Performance:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(train_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 150 × 13
    mtry trees min_n tree_depth learn_rate loss_reduction sample_size .metric   
   &lt;int&gt; &lt;int&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;     
 1    32    69    14          3       1.06           1.90       0.942 accuracy  
 2    32    69    14          3       1.06           1.90       0.942 mn_log_lo…
 3    32    69    14          3       1.06           1.90       0.942 roc_auc   
 4    28    60     9          3       1.07           1.72       0.784 accuracy  
 5    28    60     9          3       1.07           1.72       0.784 mn_log_lo…
 6    28    60     9          3       1.07           1.72       0.784 roc_auc   
 7    26    58     7          3       1.07           1.98       0.924 accuracy  
 8    26    58     7          3       1.07           1.98       0.924 mn_log_lo…
 9    26    58     7          3       1.07           1.98       0.924 roc_auc   
10    15    69    19          3       1.07           5.45       0.958 accuracy  
# ℹ 140 more rows
# ℹ 5 more variables: .estimator &lt;chr&gt;, mean &lt;dbl&gt;, n &lt;int&gt;, std_err &lt;dbl&gt;,
#   .config &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the best parameters using a single metric (e.g., `roc_auc`)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>best_params <span class="ot">&lt;-</span> xgb_tune_model <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="at">metric =</span> <span class="st">"roc_auc"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>best_params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
   mtry trees min_n tree_depth learn_rate loss_reduction sample_size .config    
  &lt;int&gt; &lt;int&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1    15    69    19          3       1.07           5.45       0.958 Preprocess…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalize the workflow with the best parameters</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>final_wf <span class="ot">&lt;-</span> wf <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_params)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the final model on the training data</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>final_fit <span class="ot">&lt;-</span> final_wf <span class="sc">%&gt;%</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>final_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: boost_tree()

── Preprocessor ────────────────────────────────────────────────────────────────
5 Recipe Steps

• step_dummy()
• step_zv()
• step_normalize()
• step_novel()
• step_other()

── Model ───────────────────────────────────────────────────────────────────────
##### xgb.Booster
raw: 54 Kb 
call:
  xgboost::xgb.train(params = list(eta = 1.06821538767645, max_depth = 3L, 
    gamma = 5.45186158492749, colsample_bytree = 1, colsample_bynode = 0.0914634146341463, 
    min_child_weight = 19L, subsample = 0.957812811527401), data = x$data, 
    nrounds = 69L, watchlist = x$watchlist, verbose = 0, early_stopping_rounds = 50, 
    scale_pos_weight = 11.354809976247, tree_method = "hist", 
    max_bin = 256, nthread = 4, verbosity = 1, objective = "binary:logistic")
params (as set within xgb.train):
  eta = "1.06821538767645", max_depth = "3", gamma = "5.45186158492749", colsample_bytree = "1", colsample_bynode = "0.0914634146341463", min_child_weight = "19", subsample = "0.957812811527401", scale_pos_weight = "11.354809976247", tree_method = "hist", max_bin = "256", nthread = "4", verbosity = "1", objective = "binary:logistic", validate_parameters = "TRUE"
xgb.attributes:
  best_iteration, best_msg, best_ntreelimit, best_score, niter
callbacks:
  cb.evaluation.log()
  cb.early.stop(stopping_rounds = early_stopping_rounds, maximize = maximize, 
    verbose = verbose)
# of features: 164 
niter: 51
best_iteration : 1 
best_ntreelimit : 1 
best_score : 0.285393 
best_msg : [1]  training-logloss:0.285393 
nfeatures : 164 
evaluation_log:
    iter training_logloss
       1        0.2853930
       2        0.2973932
---                      
      50        0.3665277
      51        0.3663267</code></pre>
</div>
</div>
</section>
<section id="evaluate-on-train-data" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-on-train-data">Evaluate on Train Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the training data</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>train_predictions <span class="ot">&lt;-</span> final_fit <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> train_data, <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine data frames: actual target values from train data and predictions (from train predictions)</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>train_results <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(train_data, train_predictions)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create class predictions based on threshold = 0.5</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>train_results <span class="ot">&lt;-</span> train_results <span class="sc">%&gt;%</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_class =</span> <span class="fu">ifelse</span>(.pred_1 <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="st">"1"</span>, <span class="st">"0"</span>))</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert `pred_class` to factor</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>train_results <span class="ot">&lt;-</span> train_results <span class="sc">%&gt;%</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_class =</span> <span class="fu">factor</span>(pred_class, <span class="at">levels =</span> <span class="fu">levels</span>(train_data<span class="sc">$</span>TARGET)))</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate on the training set</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC AUC</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>roc_auc_train <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">roc_auc</span>(train_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Log Loss</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>log_loss_train <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">mn_log_loss</span>(train_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>accuracy_train <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">accuracy</span>(train_results, <span class="at">truth =</span> TARGET, <span class="at">estimate =</span> pred_class)</span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Error (1 - Accuracy)</span></span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>accuracy_value <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(train_results, <span class="at">truth =</span> TARGET, <span class="at">estimate =</span> pred_class)</span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>error_train <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> accuracy_value<span class="sc">$</span>.estimate</span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a><span class="co">#  AUCPR (Area Under Precision-Recall Curve)</span></span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>aupr_train <span class="ot">&lt;-</span> <span class="fu">pr_auc</span>(train_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a><span class="co"># All train metrics</span></span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a>train_metrics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">Metric =</span> <span class="fu">c</span>(<span class="st">"ROC AUC"</span>, <span class="st">"Log Loss"</span>, <span class="st">"Accuracy"</span>, <span class="st">"Error"</span>, <span class="st">"AUCPR"</span>),</span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a>    roc_auc_train<span class="sc">$</span>.estimate,</span>
<span id="cb42-44"><a href="#cb42-44" aria-hidden="true" tabindex="-1"></a>    log_loss_train<span class="sc">$</span>.estimate,</span>
<span id="cb42-45"><a href="#cb42-45" aria-hidden="true" tabindex="-1"></a>    accuracy_value<span class="sc">$</span>.estimate,</span>
<span id="cb42-46"><a href="#cb42-46" aria-hidden="true" tabindex="-1"></a>    error_train,</span>
<span id="cb42-47"><a href="#cb42-47" aria-hidden="true" tabindex="-1"></a>    aupr_train<span class="sc">$</span>.estimate</span>
<span id="cb42-48"><a href="#cb42-48" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb42-49"><a href="#cb42-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-50"><a href="#cb42-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-51"><a href="#cb42-51" aria-hidden="true" tabindex="-1"></a>train_metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Metric      Value
1  ROC AUC 0.50000000
2 Log Loss 2.04846364
3 Accuracy 0.91905986
4    Error 0.08094014
5    AUCPR 0.95952993</code></pre>
</div>
</div>
</section>
<section id="evaluate-on-test-data" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-on-test-data">Evaluate on Test Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> final_fit <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> test_data, <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(test_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  .pred_0 .pred_1
    &lt;dbl&gt;   &lt;dbl&gt;
1   0.891   0.109
2   0.891   0.109
3   0.891   0.109
4   0.891   0.109
5   0.891   0.109
6   0.891   0.109</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine data frames: actual target values from test data and predictions (from test predictions)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(test_data, test_predictions)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(test_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 65
  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY
  &lt;fct&gt;  &lt;chr&gt;              &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;          
1 0      Cash loans         F           N            Y              
2 0      Cash loans         M           N            Y              
3 0      Cash loans         F           N            Y              
4 0      Revolving loans    M           N            Y              
5 0      Cash loans         F           N            Y              
6 0      Revolving loans    M           Y            Y              
# ℹ 60 more variables: CNT_CHILDREN &lt;dbl&gt;, AMT_INCOME_TOTAL &lt;dbl&gt;,
#   AMT_CREDIT &lt;dbl&gt;, AMT_ANNUITY &lt;dbl&gt;, AMT_GOODS_PRICE &lt;dbl&gt;,
#   NAME_TYPE_SUITE &lt;chr&gt;, NAME_INCOME_TYPE &lt;chr&gt;, NAME_EDUCATION_TYPE &lt;chr&gt;,
#   NAME_FAMILY_STATUS &lt;chr&gt;, NAME_HOUSING_TYPE &lt;chr&gt;,
#   REGION_POPULATION_RELATIVE &lt;dbl&gt;, DAYS_BIRTH &lt;dbl&gt;,
#   DAYS_REGISTRATION &lt;dbl&gt;, DAYS_ID_PUBLISH &lt;dbl&gt;, OWN_CAR_AGE &lt;dbl&gt;,
#   FLAG_EMP_PHONE &lt;fct&gt;, FLAG_WORK_PHONE &lt;fct&gt;, FLAG_PHONE &lt;fct&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate on the test set</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co">#test_metrics &lt;- yardstick::metrics(test_results, truth = TARGET, .pred_1) %&gt;%</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#filter(.metric %in% c("roc_auc", "mn_log_loss", "accuracy"))</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create class predictions based on threshold = 0.5</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test_results <span class="sc">%&gt;%</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">pred_class =</span> <span class="fu">ifelse</span>(.pred_1 <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="st">"1"</span>, <span class="st">"0"</span>))</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert `pred_class` to be a factor</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test_results <span class="sc">%&gt;%</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_class =</span> <span class="fu">factor</span>(pred_class, <span class="at">levels =</span> <span class="fu">levels</span>(test_results<span class="sc">$</span>TARGET)))</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert `TARGET` and `pred_class` to factors with the same levels</span></span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test_results <span class="sc">%&gt;%</span></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">TARGET =</span> <span class="fu">factor</span>(TARGET, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)),</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_class =</span> <span class="fu">factor</span>(pred_class, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>))</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC: uses class predicted probabilities</span></span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a>roc_auc_result <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">roc_auc</span>(test_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-32"><a href="#cb48-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Log Loss: uses class predicted probabilities</span></span>
<span id="cb48-33"><a href="#cb48-33" aria-hidden="true" tabindex="-1"></a>log_loss_result <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">mn_log_loss</span>(test_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb48-34"><a href="#cb48-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-35"><a href="#cb48-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy: uses factored class prediction</span></span>
<span id="cb48-36"><a href="#cb48-36" aria-hidden="true" tabindex="-1"></a>accuracy_result <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">accuracy</span>(test_results, <span class="at">truth =</span> TARGET, <span class="at">estimate =</span> pred_class)</span>
<span id="cb48-37"><a href="#cb48-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-38"><a href="#cb48-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Error </span></span>
<span id="cb48-39"><a href="#cb48-39" aria-hidden="true" tabindex="-1"></a>error_test <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">metrics</span>(test_results, <span class="at">truth =</span> TARGET, <span class="at">estimate =</span> pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb48-40"><a href="#cb48-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"accuracy"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-41"><a href="#cb48-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.estimate =</span> <span class="dv">1</span> <span class="sc">-</span> .estimate)</span>
<span id="cb48-42"><a href="#cb48-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-43"><a href="#cb48-43" aria-hidden="true" tabindex="-1"></a><span class="co"># AUCPR </span></span>
<span id="cb48-44"><a href="#cb48-44" aria-hidden="true" tabindex="-1"></a>aupr_test <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">pr_auc</span>(test_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb48-45"><a href="#cb48-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-46"><a href="#cb48-46" aria-hidden="true" tabindex="-1"></a><span class="co"># MAP (Mean Average Precision) - equivalent to precision at different recall thresholds</span></span>
<span id="cb48-47"><a href="#cb48-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-48"><a href="#cb48-48" aria-hidden="true" tabindex="-1"></a>map_test <span class="ot">&lt;-</span> yardstick<span class="sc">::</span><span class="fu">average_precision</span>(test_results, <span class="at">truth =</span> TARGET, .pred_1)</span>
<span id="cb48-49"><a href="#cb48-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-50"><a href="#cb48-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-51"><a href="#cb48-51" aria-hidden="true" tabindex="-1"></a><span class="co"># All test Metrics</span></span>
<span id="cb48-52"><a href="#cb48-52" aria-hidden="true" tabindex="-1"></a>test_metrics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb48-53"><a href="#cb48-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">Metric =</span> <span class="fu">c</span>(<span class="st">"ROC AUC"</span>, <span class="st">"Log Loss"</span>, <span class="st">"Accuracy"</span>, <span class="st">"Error"</span>, <span class="st">"AUCPR"</span>, <span class="st">"MAP"</span>),</span>
<span id="cb48-54"><a href="#cb48-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb48-55"><a href="#cb48-55" aria-hidden="true" tabindex="-1"></a>    roc_auc_result<span class="sc">$</span>.estimate,</span>
<span id="cb48-56"><a href="#cb48-56" aria-hidden="true" tabindex="-1"></a>    log_loss_result<span class="sc">$</span>.estimate,</span>
<span id="cb48-57"><a href="#cb48-57" aria-hidden="true" tabindex="-1"></a>    accuracy_result<span class="sc">$</span>.estimate,</span>
<span id="cb48-58"><a href="#cb48-58" aria-hidden="true" tabindex="-1"></a>    error_test<span class="sc">$</span>.estimate,</span>
<span id="cb48-59"><a href="#cb48-59" aria-hidden="true" tabindex="-1"></a>    aupr_test<span class="sc">$</span>.estimate,</span>
<span id="cb48-60"><a href="#cb48-60" aria-hidden="true" tabindex="-1"></a>    map_test<span class="sc">$</span>.estimate</span>
<span id="cb48-61"><a href="#cb48-61" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-62"><a href="#cb48-62" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-63"><a href="#cb48-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-64"><a href="#cb48-64" aria-hidden="true" tabindex="-1"></a>test_metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Metric      Value
1  ROC AUC 0.50000000
2 Log Loss 2.04848198
3 Accuracy 0.91906858
4    Error 0.08093142
5    AUCPR 0.95953429
6      MAP 0.91906858</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="feature-importance" class="level1">
<h1>Feature Importance</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>xgb_booster <span class="ot">&lt;-</span> <span class="fu">extract_fit_engine</span>(final_fit)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>xgb_importance <span class="ot">&lt;-</span> xgboost<span class="sc">::</span><span class="fu">xgb.importance</span>(<span class="at">model =</span> xgb_booster)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(xgb_importance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Feature       Gain      Cover   Frequency
1:                 EXT_SOURCE_3 0.25871787 0.14168321 0.077551020
2:                 EXT_SOURCE_2 0.17660937 0.06412984 0.065306122
3:                 EXT_SOURCE_1 0.07449437 0.04275258 0.044897959
4:              AMT_GOODS_PRICE 0.04857556 0.05077497 0.053061224
5: ORGANIZATION_TYPE_Unemployed 0.03849605 0.01231684 0.008163265
6:                   DAYS_BIRTH 0.03542029 0.11242377 0.053061224</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the xgb_importance data to a data frame</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>xgb_importance_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(xgb_importance)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the top 15 important features based on Gain</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>top_features <span class="ot">&lt;-</span> xgb_importance_df <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Gain)) <span class="sc">%&gt;%</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the data for ggplot2 (long format)</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>importance_long <span class="ot">&lt;-</span> top_features <span class="sc">%&gt;%</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Feature, Gain, Cover, Frequency) <span class="sc">%&gt;%</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"Gain"</span>, <span class="st">"Cover"</span>, <span class="st">"Frequency"</span>),</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">names_to =</span> <span class="st">"Measure"</span>,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>                      <span class="at">values_to =</span> <span class="st">"Importance"</span>)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(importance_long, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Feature, Importance), <span class="at">y =</span> Importance, <span class="at">fill =</span> Measure)) <span class="sc">+</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top Predictors"</span>,</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Feature"</span>,</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Importance"</span>) <span class="sc">+</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"pink"</span>, <span class="st">"lightgreen"</span>)) <span class="sc">+</span></span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modelling_nikita_pdf_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot illustrates the top predictors based on three metrics: Gain, Cover, and Frequency. Variables such as External sources, DAYS_BIRTH, AMT_GOODS_PRICE, DAYS_REGISTRATION, OWN_CAR_AGE, DAYS_LAST_PHONE_CHANGE are the most significant drivers of the model’s predictions. The Gain (green bars) indicates the relative contribution of each feature to the model’s accuracy. The Cover (blue bars) represents the proportion of observations that utilize the feature, with EXT_SOURCE_3 and DAYS_BIRTH covering a large share of the dataset. The Frequency (pink bars) shows how often the feature is used in the model’s decision trees, suggesting that external source features are critical predictors for loan default.</p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="make-predictions-with-the-test-application-data" class="level2">
<h2 class="anchored" data-anchor-id="make-predictions-with-the-test-application-data">Make Predictions with the Test Application Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure factors and the levels in `test_clean for all predictors match those in the training data for prediction</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>te_clean<span class="sc">$</span>REGION_RATING_CLIENT_W_CITY <span class="ot">&lt;-</span> <span class="fu">factor</span>(te_clean<span class="sc">$</span>REGION_RATING_CLIENT_W_CITY,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">levels</span>(train_data<span class="sc">$</span>REGION_RATING_CLIENT_W_CITY)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># remove any remaining NA's( just 1 was left)</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(te_clean<span class="sc">$</span>REGION_RATING_CLIENT_W_CITY))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>te_clean <span class="ot">&lt;-</span> te_clean[<span class="sc">!</span><span class="fu">is.na</span>(te_clean<span class="sc">$</span>REGION_RATING_CLIENT_W_CITY), ]</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data </span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>boost_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(final_fit, <span class="at">new_data =</span> te_clean, <span class="at">type =</span> <span class="st">"prob"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="format-the-predictions-into-an-acceptable-format-for-kaggle" class="level1">
<h1>Format the predictions into an acceptable format for Kaggle</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert predictions to a dataframe</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>boost_pred <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(boost_pred) </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boost_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    .pred_0   .pred_1
1 0.8912528 0.1087472
2 0.8912528 0.1087472
3 0.8912528 0.1087472
4 0.8912528 0.1087472
5 0.8912528 0.1087472
6 0.8912528 0.1087472</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>boost_pred1 <span class="ot">&lt;-</span> boost_pred <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">".pred_0"</span>) <span class="sc">%&gt;%</span> <span class="co"># Select only the zero column [ prob. of no default]</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">pull</span>() <span class="co"># Pull this column out and convert to vector.</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Update kaggle_submission with the filtered predictions</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>kaggle_submission <span class="ot">&lt;-</span> te_clean <span class="sc">%&gt;%</span> </span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SK_ID_CURR) <span class="sc">%&gt;%</span> <span class="co"># Select the ID</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SK_ID_CURR =</span> <span class="fu">as.integer</span>(SK_ID_CURR), <span class="co"># Convert SK_ID_CURR to an integer per Kaggle's requirements</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">TARGET =</span> boost_pred1) <span class="co"># Kaggle wants Target to be a column in the dataset, so create a new column called "Target" and assign all the predictions to that column</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kaggle_submission) <span class="co"># Check the first few predictions </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  SK_ID_CURR TARGET
       &lt;int&gt;  &lt;dbl&gt;
1     100001  0.891
2     100005  0.891
3     100013  0.891
4     100042  0.891
5     100057  0.891
6     100065  0.891</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify where you want to export the submissions</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Write the predictions to a csv file.</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(kaggle_submission, <span class="st">"C:/Users/nikit/Downloads/Capstone Project/kaggle_submission.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project/kaggle_submission.csv"</span>)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  SK_ID_CURR TARGET
       &lt;dbl&gt;  &lt;dbl&gt;
1     100001  0.891
2     100005  0.891
3     100013  0.891
4     100042  0.891
5     100057  0.891
6     100065  0.891</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [37,739 × 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ SK_ID_CURR: num [1:37739] 1e+05 1e+05 1e+05 1e+05 1e+05 ...
 $ TARGET    : num [1:37739] 0.891 0.891 0.891 0.891 0.891 ...
 - attr(*, "spec")=
  .. cols(
  ..   SK_ID_CURR = col_double(),
  ..   TARGET = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project/kaggle_submission.csv"</span>,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">col_types =</span> <span class="fu">cols</span>(</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">SK_ID_CURR =</span> <span class="fu">col_integer</span>(),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">TARGET =</span> <span class="fu">col_double</span>()</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>               ))</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>ks <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/nikit/Downloads/Capstone Project/kaggle_submission.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="final-interpretations-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="final-interpretations-and-conclusion">Final Interpretations and Conclusion</h2>
<p>The XGBoost model achieves an accuracy of 91.9% on the training set and 91% on the test set, but its ROC AUC of 0.5 on both sets indicates poor class discrimination, effectively performing no better than random guessing. However, its high AUC-PR scores (0.9595 for training and 0.95 for testing) suggest better handling of the minority class compared to the decision tree model, which showed high accuracy but a complete failure to identify minority instances. Unlike the decision tree, which struggled with the minority class (with a TPR of 0 and F1 score of 0), XGBoost performs better in this regard, though there’s still room for improvement. When compared to the Naive Bayes model, which had a relatively faster training time (207.415 sec) and good overall efficiency but was also weak in classifying the minority class, XGBoost shows a better balance between accuracy and handling imbalanced data. Despite its low log loss (2.048) and relatively low error (8%), further optimization could improve the discriminatory power of XGBoost.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>